install: carthage update --platform iOS
language: swift
os: osx
osx_image: xcode10
script:
  xcodebuild -scheme SwiftMusicbrainz -project SwiftMusicbrainz.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' test
after_success:
  bash <(curl -s https://codecov.io/bash)

